name: BabySync
options:
  bundleIdPrefix: app.babysync
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  SWIFT_VERSION: "6.0"
  ENABLE_USER_SCRIPT_SANDBOXING: false

packages:
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess.git
    from: "4.2.2"

targets:
  BabySync:
    type: application
    platform: iOS
    sources:
      - path: Sources
    dependencies:
      - package: KeychainAccess
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: app.babysync.ios
      INFOPLIST_FILE: Info.plist
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_STYLE: Automatic
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: BabySync
        UILaunchScreen: {}
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true

  BabySyncTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: BabySync
