name: Saga
options:
  bundleIdPrefix: app.saga
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  SWIFT_VERSION: "6.0"
  ENABLE_USER_SCRIPT_SANDBOXING: false

packages:
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess.git
    from: "4.2.2"

targets:
  Saga:
    type: application
    platform: iOS
    sources:
      - path: Sources
    dependencies:
      - package: KeychainAccess
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: app.saga.ios
      INFOPLIST_FILE: Info.plist
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_STYLE: Automatic
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: Saga
        UILaunchScreen: {}
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true

  SagaTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: Saga
    settings:
      GENERATE_INFOPLIST_FILE: true
      PRODUCT_BUNDLE_IDENTIFIER: app.saga.tests

  SagaUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: UITests
    dependencies:
      - target: Saga
    settings:
      GENERATE_INFOPLIST_FILE: true
      PRODUCT_BUNDLE_IDENTIFIER: app.saga.uitests

schemes:
  Saga:
    build:
      targets:
        Saga: all
        SagaTests: [test]
        SagaUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - SagaTests
        - SagaUITests
